version: '3.8'

services:
  app:
    image: nordenes/turnoextra:latest
    container_name: turnoextra
    environment:
      - RAILS_ENV=${RAILS_ENV}
    env_file:
      - .env.${RAILS_ENV}
    ports:
      - "3000:3000"
    volumes:
      - ./storage:/rails/storage
    restart: always
