version: '3.8'

services:
  app:
    image: nordenes/turnoextra:latest
    container_name: turnoextra
    environment:
      - RAILS_ENV=${RAILS_ENV}
    env_file:
      - .env.${RAILS_ENV}
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - app_db

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt/live:/etc/letsencrypt/live
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - app

  app_db:
    image: postgres:15
    container_name: turnoextra_db
    env_file:
      - .env.${RAILS_ENV}
    ports:
      - "5432:5432"
    volumes:
      - turnoextra_data:/var/lib/postgresql/data
    restart: always

volumes:
  turnoextra_data: