default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "postgres") %>
  host: <%= ENV.fetch("POSTGRES_HOST", "app_db") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>

development:
  <<: *default
  host: localhost
  database: turnoextra_development

test:
  <<: *default
  host: localhost
  database: turnoextra_test

production:
  primary:
    <<: *default
    database: turnoextra_production
  cache:
    <<: *default
    database: turnoextra_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: turnoextra_production_queue
    migrations_paths: db/queue_migrate
