default: &default
  dispatchers:
    - polling_interval: 30
      batch_size: 50
  workers:
    - queues: "*"
      threads: 1
      processes: 1
      polling_interval: 5

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
